CREATE TABLE `favorites` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`location_name` text NOT NULL,
	`menu_name` text NOT NULL,
	`category_name` text NOT NULL,
	`date_added` text NOT NULL,
	`link` text,
	`calories` text,
	`total_fat` text,
	`saturated_fat` text,
	`cholesterol` text,
	`sodium` text,
	`total_carbohydrates` text,
	`dietary_fiber` text,
	`total_sugars` text,
	`protein` text,
	`vitamin_d` text,
	`calcium` text,
	`iron` text,
	`potassium` text,
	`ingredients` text,
	`trans_fat` text,
	`beef` integer,
	`egg` integer,
	`fish` integer,
	`peanuts` integer,
	`pork` integer,
	`shellfish` integer,
	`soy` integer,
	`tree_nuts` integer,
	`wheat` integer,
	`sesame_seeds` integer,
	`vegan` integer,
	`vegetarian` integer,
	`halal` integer,
	`milk` integer
);
